console.log('Hiyah There!');
console.log('How\'s it goin?');
var x = 13;
console.log(typeof x);
let age = 72;
console.log(age);
let hens = 4;
let roosters = 2;
hens = hens - 1;
let chickens = hens + roosters;
console.log('--------------------------------');
let str = 'superhero';
console.log(str.slice(0, 5));
console.log('Logs: "super"');    
console.log('Fighting is entertaining.'.replace('entertaining', 'brutal'));
let strThree = 'Hiyah There';
console.log(strThree.replace('There', 'You'));
console.log(strThree);
let animal = 'dog';
let sound = 'bark';
console.log(`${animal} says ${sound}`);
let item = 'cucumbers';
let price = 1.99;
let quantity = 4;
console.log(`You bought ${quantity} ${item}, total price: $${price*quantity}`);
const minAge = 21;
let yourAge = 19;
let strFour = `You must be ${minAge} to enter. Come back in ${minAge - yourAge} years`;
console.log(strFour);
console.log('-------------------');
console.log('Math Object');