console.log('Hiyah There!');
console.log('How\'s it goin?');
var x = 13;
console.log(typeof x);
let age = 72;
console.log(age);
let hens = 4;
let roosters = 2;
hens = hens - 1;
let chickens = hens + roosters;